name: hqr
description: "A new Flutter project support gen QR banking."
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  dio: ^5.8.0+1
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo_hqr.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/image/logo_hqr.png"
  color_dark: "#ffffff"
  image_dark: "assets/image/logo_hqr.png"
  android: true
  ios: true
  fullscreen: true
  android_12:
    icon_background_color: "#ffffff"
    color: "#ffffff"
    color_dark: "#ffffff"
    image: "assets/image/hqr_960.png"
    icon_background_color_dark: "#ffffff"
    image_dark: "assets/image/hqr_960.png"
